# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bitwiselove
email: bitwiselove@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bitwiselove is the personal website and blog of Brandon Newton. Brandon
  Newton is a full-stack web developer/software engineer that specializes in
  Ruby on Rails and Javascript applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bitwiselover
github_username:  bitwiselove

# Build settings
markdown: kramdown
